apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv2
  labels:
    name: noName
spec:
  capacity:
    storage: 4
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-026e9a963e767e2b3
    fsType: ext4
