apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: " aws-ebs-sc"
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: testAffinity
